name: Actions Workflow

on:
  push:
    branches:
      - '**'  # Nome da branch que irá disparar o workflow
  pull_request:
    branches:
      - '**'  # Também executa em PRs para qualquer branch

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout Code
        uses: actions/checkout@v3

      # Instalar dependências do CMake e Qt base
      - name: Install Base Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ qtbase5-dev qttools5-dev-tools

      # Clonar e compilar o módulo Qt MQTT
      - name: Compile and Install Qt MQTT Module
        run: |
          git clone https://github.com/qt/qtmqtt.git
          cd qtmqtt
          mkdir build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=/usr
          make -j$(nproc)
          sudo make install

      # Configurar e construir o projeto
      - name: Configure and Build Project
        run: |
          mkdir -p DistributedEmbeddedSystems/digital_cluster/build
          cd DistributedEmbeddedSystems/digital_cluster/build
          cmake .. -DCMAKE_PREFIX_PATH=/usr
          make -j$(nproc)

      # Executar o script automate.sh (se necessário)
      - name: Run Automate Script
        run: |
          chmod +x DistributedEmbeddedSystems/digital_cluster/automate.sh
          DistributedEmbeddedSystems/digital_cluster/automate.sh

      # Testar ou validar saída do projeto
      - name: Run Tests
        run: echo "No tests configured yet"
