name: Generate Documentation

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  generate-docs:
    name: Generate Documentation
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout Code
        uses: actions/checkout@v3

      # Instalar Doxygen e Graphviz (dependência do Doxygen)
      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      # Gerar a documentação com o Doxygen
      - name: Generate Documentation
        run: doxygen Doxyfile

      # Commit e push da documentação gerada
      - name: Commit and Push Documentation
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update documentation [skip ci]" || echo "No changes to commit"
          git push origin ${{ github.ref }}
