name: Generate Documentation

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  generate-docs:
    name: Generate Documentation
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout Code
        uses: actions/checkout@v3

      # Instalar Doxygen
      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      # Gerar documentação
      - name: Generate Documentation
        run: |
          doxygen Doxyfile

      # Mover arquivos HTML para a raiz
      - name: Move HTML Files to Root
        run: |
          mv html/* ./
          rm -rf html

      # Fazer upload da documentação para o GitHub Pages
      - name: Deploy Documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          force_orphan: true
