name: Validate Merge

on:
  pull_request:
    branches:
      - main

jobs:
  check-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the PR is from dev
        run: |
          if [ "${{ github.base_ref }}" = "main" ] && [ "${{ github.head_ref }}" != "dev" ]; then
            echo "Merges to main are only allowed from dev branch."
            exit 1
          fi


  run-tests:
    runs-on: ubuntu-latest
    needs: check-merge  # Only runs if check-merge succeeds
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake qtbase5-dev libqt5widgets5 libqt5gui5 
          git clone -b 5.15 https://code.qt.io/qt/qtmqtt.git ./qtmqtt 
          cd qtmqtt 
          qmake 
          make 
          sudo make install

      - name: Build and Run GTests
        run: |
          cd digital_cluster
          rm -rf build
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DUSE_SANITIZER=ON ..
          make 
          ./digital_cluster_test
